# Generated by Django 3.0.1 on 2020-01-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200108_0146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
